SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SCORES = {
    'small': 10,
    'medium': 20,
    'large': 40
}
ASTEROID_MED_RADIUS = (ASTEROID_MIN_RADIUS + ASTEROID_MAX_RADIUS) / 3
ASTEROID_LARGE_RADIUS = (ASTEROID_MIN_RADIUS + ASTEROID_MAX_RADIUS) * 2 / 3

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5